# Generated by Django 4.0.6 on 2022-08-14 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_remove_producto_celular_remove_producto_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='apellidos',
        ),
    ]
