# Generated by Django 4.0.6 on 2022-08-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_remove_producto_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.CharField(max_length=10),
        ),
    ]
