# Generated by Django 4.0.6 on 2022-08-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechaCaducidad',
            field=models.CharField(default='s/n', max_length=70),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('Tips', 'Tips'), ('MisterMusculo', 'MisterMusculo'), ('Otros', 'Otros')], default='Marcas', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(default='s/n', max_length=6),
        ),
    ]
